#!/usr/bin/bash

# Determine which Dockerfile to use
if [ "$1" == "arm" ]; then
    DOCKERFILE="docker/Dockerfile_ARM"
else
    DOCKERFILE="docker/Dockerfile"
fi

echo "Building parquet-generator-builder Docker image using $DOCKERFILE"
docker build -t parquet-generator-builder -f $DOCKERFILE docker/.

echo "Building parquet-generator"
docker run \
    -v "$(pwd)":/opt/parquet-regression \
    -v "$(pwd)/.m2":/root/.m2 \
    parquet-generator-builder
